pipeline {

    agent any

    environment {
        TAG = "${BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS_ID = 'credentiale-dockerhub'
        DOCKERHUB_CREDENTIALS = credentials("${DOCKERHUB_CREDENTIALS_ID}")
        IMAGE_NAME = "${DOCKERHUB_CREDENTIALS_USR}/docker-backup"
        WORKDIR = "${env.WORKSPACE}/docker/backup/"
    }

    stages {

        stage('Test Docker') {
            steps {
                sh 'id'
                sh 'docker ps -a'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir("${WORKDIR}") {
                        dockerImage = docker.build("${IMAGE_NAME}:${TAG}")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS_ID}") {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }

            post {
                success {
                    echo "✅ Push-ul a fost efectuat cu succes pentru imaginea de backup!"
                    echo "🔗 Vezi imaginea: https://hub.docker.com/repository/docker/${IMAGE_NAME}"
                }
                failure {
                    echo "❌ Push-ul a eșuat! Verifică logurile din build."
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
